name: tammybindmount

services:
  mongodb1:
    image: mongo:latest
    container_name: mongodb1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: tammysuryana
      MONGO_INITDB_ROOT_PASSWORD: tammy9
      MONGO_INITDB_DATABASE: admin
    volumes:
      - "./data-mongo1:/data/db" ## ditulis dengan simple nanum type nya default sebagai volume 


      # buat container  mongodb dua 
  mongodb2:
    image: mongo:latest
    container_name: mongodb2
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: tammysuryana
      MONGO_INITDB_ROOT_PASSWORD: tammy9
      MONGO_INITDB_DATABASE: admin
    volumes:              ##  penyimpanan bisa ditulis dengan cara spesifik seperti ini dengan type Bind yang di arahkan ke folder local 
      - type: bind
        source: "./data-mongo2" #beri nama folder dan disimpan di mana 
        target: "/data/db"
        read_only: false
