name: tammygoangv

services:
  redis:
    image: redis
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - tamsnet

  golang-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "8080:8080"
    networks:
      - tamsnet

networks:
  tamsnet:
    name: jaringan_tammy
    driver: bridge
